name: ios

on:
  push:
    branches:
      - test-v1.23.2-2
  workflow_dispatch:
    inputs:
      version:
        description: "Version information (e.g., 1.23.2)"
        required: true

permissions:
  contents: write

env:
  ONNXRUNTIME_VERSION:
    |- # Enter release tag name or version name in workflow_dispatch. Appropriate version if not specified
    ${{ github.event.release.tag_name || github.event.inputs.version || '1.23.2' }}

jobs:
  ios:
    name: ios-${{ matrix.link_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        link_type: ["shared", "static"]

    steps:
      - name: Cache build result for ${{ env.ONNXRUNTIME_VERSION }}
        id: cache-build-result
        uses: actions/cache@v4
        with:
          path: onnxruntime-ios-${{ matrix.link_type }}-${{ env.ONNXRUNTIME_VERSION }}
          key: onnxruntime-ios-${{ matrix.link_type }}-${{ env.ONNXRUNTIME_VERSION }}-cache-v1

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-ios-${{ matrix.link_type }}

      - name: Checkout v${{ env.ONNXRUNTIME_VERSION }}
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: microsoft/onnxruntime
          submodules: true
          ref: v${{ env.ONNXRUNTIME_VERSION }}

      - name: Install dependencies on macos
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          brew install ninja
          which cmake
          cmake --version
          brew install tree
          tree --version

          brew install jq
          which jq

      - name: Patch 1
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          jq '.build_params.base += ["--cmake_extra_defines=CMAKE_POLICY_VERSION_MINIMUM=3.5"]' \
            tools/ci_build/github/apple/default_full_ios_framework_build_settings.json > output.json

          mv output.json tools/ci_build/github/apple/default_full_ios_framework_build_settings.json

          git diff .

      - name: Patch 2
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          # see https://github.com/microsoft/onnxruntime/pull/26380
          #
          jq '.build_params.base += ["--cmake_extra_defines=FLATBUFFERS_BUILD_FLATC=OFF"]' \
            tools/ci_build/github/apple/default_full_ios_framework_build_settings.json > output.json

          mv output.json tools/ci_build/github/apple/default_full_ios_framework_build_settings.json

          git diff .

      # - name: Patch 3
      #   if: steps.cache-build-result.outputs.cache-hit != 'true'
      #   shell: bash
      #   run: |
      #     jq '.build_params.base += ["--cmake_extra_defines=CMAKE_OSX_DEPLOYMENT_TARGET=16.0"]' \
      #       tools/ci_build/github/apple/default_full_ios_framework_build_settings.json > output.json
      #
      #     mv output.json tools/ci_build/github/apple/default_full_ios_framework_build_settings.json
      #
      #     git diff .

      - name: Patch 4
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          # jq '
          #     del(.build_osx_archs.macabi)
          #     | .build_osx_archs.iphonesimulator -= ["x86_64"]
          #   ' tools/ci_build/github/apple/default_full_ios_framework_build_settings.json \
          #   > tmp.json && mv tmp.json \
          #   tools/ci_build/github/apple/default_full_ios_framework_build_settings.json

          jq '
              del(.build_osx_archs.macabi)
            ' tools/ci_build/github/apple/default_full_ios_framework_build_settings.json \
            > tmp.json && mv tmp.json \
            tools/ci_build/github/apple/default_full_ios_framework_build_settings.json

          git diff .

      - name: Build onnxruntime ${{ env.ONNXRUNTIME_VERSION }} for macOS
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --version

          link_type=${{ matrix.link_type }}
          if [[ $link_type == "shared" ]]; then
            opts="--build_dynamic_framework"
          else
            opts=""
          fi

          echo "opts: $opts"

          python3 tools/ci_build/github/apple/build_apple_framework.py \
            --config Release \
            $opts \
            tools/ci_build/github/apple/default_full_ios_framework_build_settings.json

      - name: Setup tmate session
        if: false
        uses: mxschmitt/action-tmate@v3

      - name: Create onnxruntime XCFramework
        shell: bash
        run: |
          set -euo pipefail

          ls -lh build/apple_framework/intermediates/iphone*/Release/Release-*
          tree build/apple_framework/intermediates/iphone*/Release/Release-*

          BUILD_ROOT=build/apple_framework/framework_out
          OUT_DIR=
          OUT_DIR=onnxruntime-ios-${{ matrix.link_type }}-xcframework-${{ env.ONNXRUNTIME_VERSION }}
          mkdir -p $OUT_DIR
          mv -v $BUILD_ROOT/onnxruntime.xcframework $OUT_DIR

          tree $OUT_DIR/

      - name: Zip XCFramework
        run: |
          OUT_DIR=onnxruntime-ios-${{ matrix.link_type }}-xcframework-${{ env.ONNXRUNTIME_VERSION }}

          zip -r ${OUT_DIR}.zip $OUT_DIR

      - name: Upload artifact xcframework
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: onnxruntime-ios-${{ matrix.link_type }}-xcframework-${{ env.ONNXRUNTIME_VERSION }}
          path: onnxruntime-ios-${{ matrix.link_type }}-xcframework-${{ env.ONNXRUNTIME_VERSION }}.zip

      - name: Upload v${{ env.ONNXRUNTIME_VERSION }}
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: "./*.zip"
          overwrite: true
          tag: v${{ env.ONNXRUNTIME_VERSION }}
